### ISSUE TITLE
[BUG] USDT and USDC discovered but not toggled

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1505] opened 2024-11-06 16:01 UTC
**Describe the bug**
When USDT and USDC get auto discovered on chains, they do not get toggled in the `Choose Token `section and can't be removed

**To Reproduce**
1. Go to any EVM chain
2. auto discover tokens, if USDT or UDSC is held
3. See error

**Expected behavior**
Able to deselect if auto discovered

**Screenshots**
![Image](https://github.com/user-attachments/assets/3caed6e9-e2b6-434d-b69c-eb76511ce975)
![Image](https://github.com/user-attachments/assets/0470f3eb-ca7d-4711-a149-63a39cf2af99)

 - Version 1.6.0

**Comment by johnnyluo** [comment] 2024-12-01 20:56
This is duplicate of #1617

**Comment by enriquesouza** [comment] 2024-12-11 02:34
Hum... so we should probably removes the hardcoded one.

**Comment by enriquesouza** [comment] 2024-12-20 01:17
I solved this one last week

**Closed by enriquesouza** 2024-12-20 01:17 UTC
Labels: bug

**Comment by realpaaao** [comment] 2024-12-23 08:15
QA done.
