### ISSUE TITLE
[BUG:IPAD] Instability on chain selection, iPad

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#644] opened 2024-06-08 20:45 UTC
**Describe the bug**
If  in `ChainSelectionView` and selecting/deselecting tokens and exiting the app and opening it again it is possible to produce crashes.
I could reproduce it consitently but not determine exactly after which action.

**To Reproduce**
1. Go to `ChainSelectionView`
2. Click on different chains and toggle them
3. leave app without closing `ChainSelectionView`
4. enter app again
5. re-do steps 2. to 4. until cras

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: 17.5.1
 - Version 28

**Additional context**
See Testlight crashes and can request video from me.

**Comment by johnnyluo** [comment] 2024-06-10 00:05
It seems you app has corrupt data , the crash is caused by swiftdata

**Comment by johnnyluo** [comment] 2024-06-10 00:08
the same reason for #645

**Comment by realpaaao** [comment] 2024-06-10 13:31
> It seems you app has corrupt data , the crash is caused by swiftdata

@johnnyluo yes therefore I reinstalled it yesterday but after reinstall and import it crashed. Did another reinstall just now and fixed #645 and will observe further. 
Any idea why it got corrupted? Could happen for user too?

**Comment by johnnyluo** [comment] 2024-06-16 01:06
I am not sure why it happened, I will close it for now , we can reopen this issue if we can consistently reproduce it.

**Closed by johnnyluo** 2024-06-16 01:06 UTC
Labels: bug, crash
