### ISSUE TITLE
[BUG] Backup banner on macOS not working

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1277] opened 2024-10-07 10:56 UTC
**Describe the bug**
on macOS the backup banner is not clickable

**Expected behavior**
Able to interact

 - Version 1.2.1

**Comment by Rockindash** [comment] 2024-10-10 02:03
Closing this issue since I cannot reproduce it on my Mac.

**Closed by Rockindash** 2024-10-10 02:03 UTC
Labels: bug
