### ISSUE TITLE
BUG: Assets do not update on switch on Swap screen

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1100] opened 2024-08-28 12:11 UTC
**Describe the bug**
When switching assets in `from` and `to` the amounts do not get swapped.

**To Reproduce**
1. Go to Swap screen
2. Select two assets and input amount
3. switch assets

**Expected behavior**
Erase `from` amount when flipping tokens

**Screenshots**

https://github.com/user-attachments/assets/ce2e218c-3c89-4b0a-8557-fb14ecb79ed8

-v48

**Comment by flypaper0** [comment] 2024-10-31 08:07
could not reproduce, issue contains android screen record

**Comment by realpaaao** [comment] 2024-11-04 20:04
@flypaper0 is an android screen though that still also happens on iOS.
CAn we improve logic that if swap quote is found and switching the assets that the last amount of the quote also gets swapped?

**Comment by johnnyluo** [comment] 2024-11-11 23:01
This looks like an android issue , close it here

**Closed by johnnyluo** 2024-11-11 23:01 UTC
Labels: bug
