### ISSUE TITLE
[ADD] Fastsign for Thorchain FUNCTION-based transactions.

### ISSUE THREAD

**Issue by blushingchives** [vultisig/vultisig-ios#1429] opened 2024-10-26 04:06 UTC
Currently making a BOND transaction opens up a pair signing page (the one with the qr code). However, if a fast vault is used, this pair signing page will still be displayed and a fast sign cannot be done.

**Comment by johnnyluo** [comment] 2024-11-03 21:36
duplicate of #1478

**Closed by johnnyluo** 2024-11-03 21:36 UTC
