### ISSUE TITLE
[BUG] iPhone SE crashes on Keysign and Keygen

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#971] opened 2024-08-01 07:13 UTC
A user reported that both of his iPhone SE are crashing on scanning the QR code.
As SE also had different UI problems etc. it feels like on SE are happening more edge case bugs.

here is crash report: 
[TestFlight feedback.zip](https://github.com/user-attachments/files/16451667/TestFlight.feedback.zip)

Please investigate

**Comment by realpaaao** [comment] 2024-08-02 09:10
@johnnyluo do you have an idea what it could be?

**Comment by johnnyluo** [comment] 2024-08-15 08:49
Well, I don't have an Iphone SE , but when I use simulator , it works fine

**Comment by realpaaao** [comment] 2024-08-16 14:07
I also couldn't reproduce.. I guess it is something on the actual device... Not sure how we could pin it down...

**Comment by johnnyluo** [comment] 2024-09-15 23:18
can't reproduce , closing

**Closed by johnnyluo** 2024-09-15 23:18 UTC
Labels: bug, crash, iPhone
