### ISSUE TITLE
[BUG] Cannot save tokens

### ISSUE THREAD

**Issue by Rockindash** [vultisig/vultisig-ios#1192] opened 2024-09-23 18:23 UTC
**Describe the bug**
Does not save tokens on selection from the list.

**To Reproduce**
1) ETH -> Choose tokens
2) search token -> choose -> save
3) doesn't save

**Comment by johnnyluo** [comment] 2024-09-24 22:45
I tried this , but can't reproduce it

**Comment by johnnyluo** [comment] 2024-09-30 23:41
Can't reproduce it , closing

**Closed by johnnyluo** 2024-09-30 23:41 UTC
Labels: bug
