### ISSUE TITLE
[BUG] Auto discovered tokens do not get enabled

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1617] opened 2024-11-28 17:38 UTC
**Describe the bug**
Automatically discovered tokens will not get enabled in tokens list

**To Reproduce**
1. auto discover tokens
2. go to token list
3. See error

**Expected behavior**
Enable in token list

**Screenshots**
![Image](https://github.com/user-attachments/assets/bdd607ed-22c2-4efd-adfc-7266644286a4)

System:

**Comment by johnnyluo** [comment] 2024-12-01 20:56
duplicate of 1505 , closing, in favor of 1505

**Closed by johnnyluo** 2024-12-01 20:56 UTC
Labels: bug
