### ISSUE TITLE
[BUG] Ugly error when trying to pair 3 devices (where 2 out of 3 were already paired with another vault)

### ISSUE THREAD

**Issue by gdubicki** [vultisig/vultisig-ios#853] opened 2024-07-07 19:08 UTC
App version: 1.0 (build 36)

**Describe the bug**

I created a vault using 2 devices, my Mac and iPhone. Then I wanted to create another vault using 3 devices, 2 Macs and an iPhone.

I initiated it on the iPhone, where I already had the vault. I didn't get any warning that would suggest that it will fail because I already have a vault.

During the vault creation I got the following error:

```
Resharing key failed
failed to get old threshold: invalid input
```
(see the screenshot below)

When I deleted the old vault (it was empty) and initiated the whole process again on 3 devices, it went through without any issue.

I am only guessing that the problem is caused by the old vault still existing but maybe it was in fact something else.

**To Reproduce**

_I haven't actually did this whole process again to test if it's reproducible_, but what I did was:
1. Create a Vault using iPhone and a Mac (as an iPad)
2. Initiate creating another vault from the same iPhone, with the same Mac and another, new one

**Expected behavior**

If you can't create another vault with an existing one, you should get such a message and new vault creation should not be possible.

If it's not the reason, then I expect it to work.

**Screenshots**

<img width="741" alt="Screenshot 2024-07-03 at 20 37 20" src="https://github.com/vultisig/vultisig-ios/assets/566632/0b90dce5-a897-468d-9ef2-48b78231e818">

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.5 (23F79)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 mini
 - OS: iOS 17.5.1

**Comment by realpaaao** [comment] 2024-07-27 06:15
@gdubicki could you explain how you create a new vault after the first one?
As the error "Resharing failed" only comes up when you try to reshare an existing vault.

Creating a new vault with already used devices works

**Comment by realpaaao** [comment] 2024-08-26 14:04
Closing, can't reproduce and no feedback

**Closed by realpaaao** 2024-08-26 14:04 UTC
Labels: bug
